In [3]:
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 44.8MB/s]


(534, 800)

**CÂU 12: LIGHTNESS**

In [8]:
import matplotlib.image as mpimg
import numpy as np

img = mpimg.imread("/content/dog.jpeg")

def light_ness(vector) :
  return np.max(vector) * 0.5 + np.min(vector) * 0.5
gray_img_01 = np.apply_along_axis(light_ness, axis = 2, arr = img)
gray_img_01[0 , 0]

102.5

** CÂU 13: AVERAGE**

In [7]:
def compute_average(vector):
  return vector.mean()
gray_img_02 = np.apply_along_axis(compute_average, axis = 2, arr = img)
gray_img_02[0 , 0]

107.66666666666667

**CÂU 14: Luminosity**

In [9]:
def compute_luminosity(vector):
  return vector[0] * 0.21 + vector[1] * 0.72 + vector[2] * 0.07
gray_img_03 = np.apply_along_axis(compute_luminosity, axis = 2, arr = img)
gray_img_03[0 , 0]

126.22999999999999

**BÀI TẬP 3:**


In [11]:
! gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 10.9MB/s]


In [13]:
import pandas as pd
df = pd.read_csv("/content/advertising.csv")
data = df.to_numpy()

In [15]:
data_test = data[: 5]
print(data_test)

[[230.1  37.8  69.2  22.1]
 [ 44.5  39.3  45.1  10.4]
 [ 17.2  45.9  69.3  12. ]
 [151.5  41.3  58.5  16.5]
 [180.8  10.8  58.4  17.9]]


In [16]:
tv_data = data[:, 0]
print(tv_data.mean())

147.0425


In [17]:
sale_data = data[: , 3]
sale_mean = sale_data.mean()
scores = np.where(sale_data > sale_mean, "Good", np.where(sale_data < sale_mean, "Bad", "Average"))
print(scores[7 : 10])

['Bad' 'Bad' 'Good']


In [22]:
sale_data = data[: , 3]
sale_mean = sale_data.mean()

res_data = abs(sale_data - sale_mean)
average_min = np.argmin(res_data)
scores = np.where(sale_data > sale_data[average_min], "Good", np.where(sale_data < sale_data[average_min], "Bad", "Average"))
print(scores[7 : 10])

['Bad' 'Bad' 'Good']
