**KNN**

In [42]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

iris_X, iris_y = datasets.load_iris(return_X_y = True)

X_train, X_test, y_train, y_test = train_test_split(
    iris_X,
    iris_y,
    test_size = 0.2,
    random_state = 42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

knn_classifier = KNeighborsClassifier(n_neighbors= 5)
knn_classifier.fit(X_train, y_train)

y_pred = knn_classifier.predict(X_test)
accuracy_score(y_test, y_pred)




1.0

In [ ]:
!pip install -q datasets
import numpy as np
from datasets import load_dataset
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score

imdb= load_dataset('imdb')
imdb_train, imdb_test = imdb['train'], imdb['test']

vectorizer = CountVectorizer(max_features = 1000)
X_train = vectorizer.fit_transform(imdb_train['text']).toarray()
X_test = vectorizer.transform(imdb_test['text']).toarray()

y_train = np.array(imdb_train['label'])
y_test = np.array(imdb_test['label'])

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

knn_classifier = KNeighborsClassifier(n_neighbors = 1, algorithm = 'ball_tree')
knn_classifier.fit(X_train, y_train)

y_pred = knn_classifier.predict(X_test)
accuracy_score(y_test, y_pred)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

**K-mean**

In [33]:
import numpy as np

# dataset
data = np.array([
    [2.0, 3.0, 1.5],
    [3.0, 3.5, 2.0],
    [3.5, 3.0, 2.5],
    [8.0, 8.0, 7.5],
    [8.5, 8.5, 8.0],
    [9.0, 8.0, 8.5],
    [1.0, 2.0, 1.0],
    [1.5, 2.5, 1.5]
])

data.shape

(8, 3)

In [34]:
centroids = np.array([[2.0, 3.0, 1.5], [1.0, 2.0, 1.0], [3.0, 3.5, 2.0]])
centroids.shape

(3, 3)

In [35]:
data = data[:, np.newaxis, :]
data

array([[[2. , 3. , 1.5]],

       [[3. , 3.5, 2. ]],

       [[3.5, 3. , 2.5]],

       [[8. , 8. , 7.5]],

       [[8.5, 8.5, 8. ]],

       [[9. , 8. , 8.5]],

       [[1. , 2. , 1. ]],

       [[1.5, 2.5, 1.5]]])

In [38]:
iter = 10
for i in range(iter):
  # compute distance
  distances = np.sqrt(np.sum(np.square(data - centroids), axis = 2))

  print(distances)

  #labels:
  labels = np.argmin(distances, axis = 1)
  print(labels)

  # X = [data[labels == j].mean(axis = 0) for j in range(2)]
  # print(X)
  # break
  #updates centroids:
  new_centroids = np.array([data[labels == j].mean(axis = 0) for j in range(3)]).reshape(3, 3)
  print(new_centroids)
  print(new_centroids.shape)


  #check:
  if np.all(centroids == new_centroids):
    break
  centroids = new_centroids



[[ 0.          1.5         1.22474487]
 [ 1.22474487  2.6925824   0.        ]
 [ 1.80277564  3.082207    0.8660254 ]
 [ 9.8488578  11.28051417  8.6890736 ]
 [10.71214264 12.1449578   9.55248659]
 [11.09053651 12.5         9.92471662]
 [ 1.5         0.          2.6925824 ]
 [ 0.70710678  0.8660254   1.87082869]]
[0 2 2 2 2 2 1 0]
[[1.75 2.75 1.5 ]
 [1.   2.   1.  ]
 [6.4  6.2  5.7 ]]
(3, 3)
[[ 0.35355339  1.5         6.87313611]
 [ 1.5411035   2.6925824   5.70438428]
 [ 2.0310096   3.082207    5.37494186]
 [10.13039979 11.28051417  3.00665928]
 [10.99431671 12.1449578   3.87169214]
 [11.36331818 12.5         4.22374242]
 [ 1.17260394  0.          8.3       ]
 [ 0.35355339  0.8660254   7.43908597]]
[0 0 0 2 2 2 1 0]
[[2.5        3.         1.875     ]
 [1.         2.         1.        ]
 [8.5        8.16666667 8.        ]]
(3, 3)
[[ 0.625       1.5        10.54487764]
 [ 0.71807033  2.6925824   9.38231196]
 [ 1.17924764  3.082207    9.05231708]
 [ 9.32151409 11.28051417  0.72648316]
 [10